module.exports = {
    Function: [{
        FunctionId: "goodsAction",
        FunctionParentId: "99",
        FunctionName: "商品管理",
        Lavel: 1, // 层级
        Sort: 30, // 排序
        ChoseFlag: 2 // 1:选中，2:未选择，3：子元素有选择
    }, {
        FunctionId: "goodsQry",
        FunctionParentId: "goodsAction",
        FunctionName: "商品查询",
        Lavel: 2,
        Sort: 13,
        ChoseFlag: 2
    }, {
        FunctionId: "goodsAdd",
        FunctionParentId: "goodsAction",
        FunctionName: "商品新增",
        Lavel: 2,
        Sort: 14,
        ChoseFlag: 2
    }, {
        FunctionId: "goodsDel",
        FunctionParentId: "goodsAction",
        FunctionName: "商品删除",
        Lavel: 2,
        Sort: 15,
        ChoseFlag: 2
    }, {
        FunctionId: "goodsUpt",
        FunctionParentId: "goodsAction",
        FunctionName: "商品修改",
        Lavel: 2,
        Sort: 16,
        ChoseFlag: 2
    }, {
        FunctionId: "typeAdd",
        FunctionParentId: "goodsAction",
        FunctionName: "商品分类新增",
        Lavel: 2,
        Sort: 17,
        ChoseFlag: 2
    }, {
        FunctionId: "typeDel",
        FunctionParentId: "goodsAction",
        FunctionName: "商品分类删除",
        Lavel: 2,
        Sort: 18,
        ChoseFlag: 2
    }, {
        FunctionId: "typeUpt",
        FunctionParentId: "goodsAction",
        FunctionName: "商品分类修改",
        Lavel: 2,
        Sort: 19,
        ChoseFlag: 2
    }, {
        FunctionId: "barCodeQryGoods",
        FunctionParentId: "goodsAction",
        FunctionName: "条形码查询商品",
        Lavel: 2,
        Sort: 20,
        ChoseFlag: 2
    }, {
        FunctionId: "payType",
        FunctionParentId: "99",
        FunctionName: "支付方式管理",
        Lavel: 1,
        Sort: 27,
        ChoseFlag: 2
    }, {
        FunctionId: "casher",
        FunctionParentId: "99",
        FunctionName: "POS收款",
        Lavel: 1,
        Sort: 24,
        ChoseFlag: 2
    }, {
        FunctionId: "genBill",
        FunctionParentId: "99",
        FunctionName: "POS开单",
        Lavel: 1,
        Sort: 21,
        ChoseFlag: 2
    }, {
        FunctionId: "wchatCasher",
        FunctionParentId: "99",
        FunctionName: "小程序收款",
        Lavel: 1,
        Sort: 31,
        ChoseFlag: 2
    }, {
        FunctionId: "wchatGenBill",
        FunctionParentId: "99",
        FunctionName: "小程序开单",
        Lavel: 1,
        Sort: 32,
        ChoseFlag: 2
    }, {
        FunctionId: "myTrans",
        FunctionParentId: "99",
        FunctionName: "我的收入",
        Lavel: 1,
        Sort: 25,
        ChoseFlag: 2
    }, {
        FunctionId: "voidSale",
        FunctionParentId: "myTrans",
        FunctionName: "交易撤销",
        Lavel: 2,
        Sort: 22,
        ChoseFlag: 2
    }, {
        FunctionId: "refund",
        FunctionParentId: "myTrans",
        FunctionName: "交易退货",
        Lavel: 2,
        Sort: 23,
        ChoseFlag: 2
    }, {
        FunctionId: "storeAction",
        FunctionParentId: "99",
        FunctionName: "店铺管理",
        Lavel: 1,
        Sort: 28,
        ChoseFlag: 2
    }, {
        FunctionId: "storeUpt",
        FunctionParentId: "storeAction",
        FunctionName: "修改店铺基本信息",
        Lavel: 2,
        Sort: 1,
        ChoseFlag: 2
    }, {
        FunctionId: "operQry",
        FunctionParentId: "storeAction",
        FunctionName: "查询店铺操作员列表",
        Lavel: 2,
        Sort: 2,
        ChoseFlag: 2
    }, {
        FunctionId: "getTids",
        FunctionParentId: "storeAction",
        FunctionName: "查询当前店铺终端",
        Lavel: 2,
        Sort: 9,
        ChoseFlag: 2
    }, {
        FunctionId: "getStoreIncome",
        FunctionParentId: "storeAction",
        FunctionName: "查询当前店铺收入",
        Lavel: 2,
        Sort: 10,
        ChoseFlag: 2
    }, {
        FunctionId: "roleQry",
        FunctionParentId: "storeAction",
        FunctionName: "查询店铺角色列表",
        Lavel: 2,
        Sort: 3,
        ChoseFlag: 2
    }, {
        FunctionId: "roleAdd",
        FunctionParentId: "storeAction",
        FunctionName: "新增店铺角色",
        Lavel: 2,
        Sort: 4,
        ChoseFlag: 2
    }, {
        FunctionId: "rolePriUpt",
        FunctionParentId: "storeAction",
        FunctionName: "修改店铺角色权限",
        Lavel: 2,
        Sort: 5,
        ChoseFlag: 2
    }, {
        FunctionId: "roleDel",
        FunctionParentId: "storeAction",
        FunctionName: "删除店铺角色",
        Lavel: 2,
        Sort: 6,
        ChoseFlag: 2
    }, {
        FunctionId: "operAdd",
        FunctionParentId: "storeAction",
        FunctionName: "新增操作员",
        Lavel: 2,
        Sort: 7,
        ChoseFlag: 2
    }, {
        FunctionId: "operDel",
        FunctionParentId: "storeAction",
        FunctionName: "删除操作员",
        Lavel: 2,
        Sort: 8,
        ChoseFlag: 2
    }, {
        FunctionId: "getQrCodeVal",
        FunctionParentId: "storeAction",
        FunctionName: "生成终端及二维码对应值",
        Lavel: 2,
        Sort: 26,
        ChoseFlag: 2
    }, {
        FunctionId: "tidsUpt",
        FunctionParentId: "storeAction",
        FunctionName: "修改终端名称",
        Lavel: 2,
        Sort: 11,
        ChoseFlag: 2
    }, {
        FunctionId: "userAction",
        FunctionParentId: "99",
        FunctionName: "用户管理",
        Lavel: 1,
        Sort: 29,
        ChoseFlag: 2
    }, {
        FunctionId: "operRolesUpt",
        FunctionParentId: "userAction",
        FunctionName: "修改操作员角色",
        Lavel: 2,
        Sort: 12,
        ChoseFlag: 2
    }],
    Pay: [
        {
            Id: 'CasherPay',
            Name: '现金',
            Sort: 1,
            Type: '1'
        },
        {
            Id: 'AliPay',
            Name: '支付宝',
            Sort: 2,
            Type: '2'
        }, {
            Id: 'WeChatPay',
            Name: '微信',
            Sort: 3,
            Type: '3'
        },
        {
            Id: 'BankCardPay',
            Name: '银行卡',
            Sort: 4,
            Type: '4'
        },
        {
            Id: 'ThirdPay',
            Name: '第三方',
            Sort: 5,
            Type: '5'
        },
        {
            Id: 'EpCardPay',
            Name: '储值卡',
            Sort: 6,
            Type: '6'
        },
        {
            Id: 'CouponPay',
            Name: '券',
            Sort: 7,
            Type: '7'
        },
        {
            Id: 'MixPay',
            Name: '组合支付',
            Sort: 8,
            Type: '0'
        },
        {
            Id: 'UnionQrPay',
            Name: '云闪付',
            Sort: 9,
            Type: '10'
        },
        {
            Id: 'CashCouponPay',
            Name: '现金券',
            Sort: 10,
            Type: '11'
        },
        {
            Id: 'ICBCQrPay',
            Name: '工银E支付',
            Sort: 11,
            Type: '12'
        }]

}
