/*!
* gaozh v1
*/
module.exports = {
    // 打包配置
    R: [{
        Desc: "Function",
        Val: "R001",
        Rr: [{
            Desc: "Id",
            Val: "Rr001"
        }, {
            Desc: "ParentId",
            Val: "Rr053"
        }, {
            Desc: "Name",
            Val: "Rr054"
        }, {
            Desc: "Desc",
            Val: "Rr131"
        }, {
            Desc: "Status",
            Val: "Rr132"
        }]
    }, {
        Desc: "Goods",
        Val: "R002",
        Rr: [{
            Desc: "AddDate",
            Val: "Rr002"
        }, {
            Desc: "EditDate",
            Val: "Rr003"
        }, {
            Desc: "Id",
            Val: "Rr004"
        }, {
            Desc: "Img",
            Val: "Rr005"
        }, {
            Desc: "Num",
            Val: "Rr006"
        }, {
            Desc: "RefundNum",
            Val: "Rr007"
        }, {
            Desc: "Name",
            Val: "Rr008"
        }, {
            Desc: "StockFlag",
            Val: "Rr009"
        }, {
            Desc: "Stock",
            Val: "Rr010"
        }, {
            Desc: "StockNum",
            Val: "Rr011"
        }, {
            Desc: "Spec",
            Val: "Rr012"
        }, {
            Desc: "TypeId",
            Val: "Rr013"
        }, {
            Desc: "TypeName",
            Val: "Rr014"
        }, {
            Desc: "Unit",
            Val: "Rr015"
        }, {
            Desc: "RetailPrice",
            Val: "Rr016"
        }, {
            Desc: "OperCode",
            Val: "Rr017"
        }, {
            Desc: "BarCode",
            Val: "Rr059"
        }, {
            Desc: "BarCodeImg",
            Val: "Rr060"
        }, {
            Desc: "TradeMark",
            Val: "Rr061"
        }, {
            Desc: "ManuName",
            Val: "Rr062"
        }, {
            Desc: "Producer",
            Val: "Rr063"
        }, {
            Desc: "AssociatorPrice",
            Val: "Rr075"
        }, {
            Desc: "ManuAddress",
            Val: "Rr076"
        }, {
            Desc: "PyCode",
            Val: "Rr080"
        }]
    }, {
        Desc: "Unit",
        Val: "R003",
        Rr: [{
            Desc: "Id",
            Val: "Rr018"
        }, {
            Desc: "Name",
            Val: "Rr019"
        }]
    }, {
        Desc: "GoodsType",
        Val: "R004",
        Rr: [{
            Desc: "Id",
            Val: "Rr013"
        }, {
            Desc: "Name",
            Val: "Rr014"
        }, {
            Desc: "OperCode",
            Val: "Rr044"
        }]
    }, {
        Desc: "Pay",
        Val: "R005",
        Rr: [{
            Desc: "PayId",
            Val: "Rr020"
        }, {
            Desc: "PaySeq",
            Val: "Rr021"
        }, {
            Desc: "PayType",
            Val: "Rr022"
        }, {
            Desc: "PayAccount",
            Val: "Rr023"
        }, {
            Desc: "PayStatus",
            Val: "Rr024"
        }, {
            Desc: "TransAmt",
            Val: "Rr025"
        }, {
            Desc: "RefundAmt",
            Val: "Rr026"
        }, {
            Desc: "RealAmt",
            Val: "Rr027"
        }, {
            Desc: "SaleId",
            Val: "Rr028"
        }, {
            Desc: "OrgPayId",
            Val: "Rr029"
        }]
    }, {
        Desc: "Trans",
        Val: "R006",
        Rr: [{
            Desc: "OrgTransId",
            Val: "Rr030"
        }, {
            Desc: "TransId",
            Val: "Rr031"
        }, {
            Desc: "TransType",
            Val: "Rr032"
        }, {
            Desc: "Tid",
            Val: "Rr033"
        }, {
            Desc: "TotalAmt",
            Val: "Rr034"
        }, {
            Desc: "RealAmt",
            Val: "Rr035"
        }, {
            Desc: "RefundAmt",
            Val: "Rr036"
        }, {
            Desc: "PayMode",
            Val: "Rr037"
        }, {
            Desc: "Mid",
            Val: "Rr038"
        }, {
            Desc: "StoreId",
            Val: "Rr039"
        }, {
            Desc: "UserMobile",
            Val: "Rr040"
        }, {
            Desc: "Status",
            Val: "Rr041"
        }, {
            Desc: "TransDate",
            Val: "Rr042"
        }, {
            Desc: "PayType",
            Val: "Rr043"
        }, {
            Desc: "TransChannel",
            Val: "Rr137"
        }, {
            Desc: "StoreName",
            Val: "Rr209"
        }]
    }, {
        Desc: "Users",
        Val: "R007",
        Rr: [{
            Desc: "UserId",
            Val: "Rr055"
        }, {
            Desc: "UserMobile",
            Val: "Rr045"
        }, {
            Desc: "Name",
            Val: "Rr046"
        }, {
            Desc: "Addr",
            Val: "Rr047"
        }, {
            Desc: "Status",
            Val: "Rr048"
        }, {
            Desc: "CreateDate",
            Val: "Rr133"
        }, {
            Desc: "ModifyDate",
            Val: "Rr134"
        }, {
            Desc: "ModifyUser",
            Val: "Rr135"
        }, {
            Desc: "UserLvl",
            Val: "Rr197"
        }]
    }, {
        Desc: "Roles",
        Val: "R008",
        Rr: [{
            Desc: "Id",
            Val: "Rr049"
        }, {
            Desc: "Name",
            Val: "Rr050"
        }, {
            Desc: "Desc",
            Val: "Rr051"
        }, {
            Desc: "Owner",
            Val: "Rr052"
        }]
    }, {
        Desc: "Stores",
        Val: "R009",
        Rr: [{
            Desc: "StoreId",
            Val: "Rr056"
        }, {
            Desc: "StoreIssuid",
            Val: "Rr057"
        }, {
            Desc: "StoreName",
            Val: "Rr058"
        }, {
            Desc: "StoreCacType",
            Val: "Rr066"
        }, {
            Desc: "StoreStockControl",
            Val: "Rr067"
        }, {
            Desc: "StoreLevel",
            Val: "Rr068"
        }, {
            Desc: "StoreProvince",
            Val: "Rr069"
        }, {
            Desc: "StoreCity",
            Val: "Rr066"
        }, {
            Desc: "StoreCacType",
            Val: "Rr070"
        }, {
            Desc: "StoreArea",
            Val: "Rr071"
        }, {
            Desc: "StoreAddr",
            Val: "Rr072"
        }, {
            Desc: "StoreDate",
            Val: "Rr073"
        }, {
            Desc: "StoreStatus",
            Val: "Rr074"
        }, {
            Desc: "StoreMobile",
            Val: "Rr206"
        }, {
            Desc: "StoreUserName",
            Val: "Rr207"
        }, {
            Desc: "StoreTidNum",
            Val: "Rr208"
        }]
    }, {
        Desc: "Tids",
        Val: "R010",
        Rr: [{
            Desc: "Tid",
            Val: "Rr077"
        }, {
            Desc: "TidFlag",
            Val: "Rr078"
        }, {
            Desc: "Name",
            Val: "Rr079"
        }]
    },


        {
            Desc: "RTrans",
            Val: "R013",
            Rr: [{
                Desc: "TransId",
                Val: "Rr095"
            }, {
                Desc: "PayMode",
                Val: "Rr096"
            }, {
                Desc: "PayType",
                Val: "Rr097"
            }, {
                Desc: "PayType",
                Val: "Rr097"
            }, {
                Desc: "RealAmt",
                Val: "Rr098"
            }, {
                Desc: "TransDate",
                Val: "Rr099"
            }, {
                Desc: "UserMobile",
                Val: "Rr101"
            }, {
                Desc: "Status",
                Val: "Rr100"
            }]
        },


        {
            Desc: "UserActSum",
            Val: "R015",
            Rr: [{
                Desc: "Date",
                Val: "Rr110"
            }, {
                Desc: "UserRgst",
                Val: "Rr111"
            }, {
                Desc: "StoreRgst",
                Val: "Rr112"
            }, {
                Desc: "TidRgst",
                Val: "Rr113"
            }, {
                Desc: "GoodsAdd",
                Val: "Rr114"
            }, {
                Desc: "GdsAddS",
                Val: "Rr115"
            }, {
                Desc: "MobileLg",
                Val: "Rr116"
            }, {
                Desc: "PosLg",
                Val: "Rr117"
            }]
        }, {
            Desc: "TransSum",
            Val: "R016",
            Rr: [{
                Desc: "Date",
                Val: "Rr118"
            }, {
                Desc: "Cnt",
                Val: "Rr119"
            }, {
                Desc: "TotalAmt",
                Val: "Rr120"
            }, {
                Desc: "RealAmt",
                Val: "Rr121"
            }, {
                Desc: "RCnt",
                Val: "Rr122"
            }, {
                Desc: "RTotalAmt",
                Val: "Rr123"
            }, {
                Desc: "RRealAmt",
                Val: "Rr124"
            }]
        }, {
            Desc: "PayTypeSum",
            Val: "R017",
            Rr: [{
                Desc: "Date",
                Val: "Rr125"
            }, {
                Desc: "Type",
                Val: "Rr126"
            }, {
                Desc: "SaleCnt",
                Val: "Rr127"
            }, {
                Desc: "SaleAmt",
                Val: "Rr128"
            }, {
                Desc: "RefCnt",
                Val: "Rr129"
            }, {
                Desc: "RefAmt",
                Val: "Rr130"
            }]
        },


        {
            Desc: "Insts",
            Val: "R023",
            Rr: [{
                Desc: "InstId",
                Val: "Rr181"
            }, {
                Desc: "AreaCode",
                Val: "Rr182"
            }, {
                Desc: "InstName",
                Val: "Rr183"
            }, {
                Desc: "ParentInstId",
                Val: "Rr184"
            }, {
                Desc: "LinkMan",
                Val: "Rr185"
            }, {
                Desc: "Phone",
                Val: "Rr186"
            }, {
                Desc: "MngId",
                Val: "Rr187"
            }, {
                Desc: "MngTag",
                Val: "Rr188"
            }, {
                Desc: "IssuTag",
                Val: "Rr189"
            }, {
                Desc: "AcqTag",
                Val: "Rr190"
            }, {
                Desc: "FwdTag",
                Val: "Rr191"
            }, {
                Desc: "Memo",
                Val: "Rr192"
            }, {
                Desc: "Teller",
                Val: "Rr193"
            }, {
                Desc: "ModiDate",
                Val: "Rr194"
            }, {
                Desc: "Status",
                Val: "Rr195"
            }, {
                Desc: "PayTypeMap",
                Val: "Rr196"
            }]
        },
        {
            Desc: "PayTypeReport",
            Val: "R024",
            Rr: [{
                Desc: "StoreId",
                Val: "Rr201"
            }, {
                Desc: "SettleDate",
                Val: "Rr202"
            }, {
                Desc: "Cnt",
                Val: "Rr203"
            }, {
                Desc: "PayType",
                Val: "Rr204"
            }, {
                Desc: "StoreName",
                Val: "Rr220"
            }, {
                Desc: "Amt",
                Val: "Rr205"
            }]
        }, {
            Desc: "StoreGrp",
            Val: "R025",
            Rr: [{
                Desc: "Id",
                Val: "Rr198"
            }, {
                Desc: "Name",
                Val: "Rr199"
            }, {
                Desc: "Status",
                Val: "Rr200"
            }]
        }, {
            Desc: "PayTrans",
            Val: "R026",
            Rr: [{
                Desc: "StoreId",
                Val: "Rr210"
            }, {
                Desc: "StoreName",
                Val: "Rr219"
            }, {
                Desc: "TransType",
                Val: "Rr211"
            }, {
                Desc: "TransId",
                Val: "Rr212"
            }, {
                Desc: "PaySeq",
                Val: "Rr213"
            }, {
                Desc: "PayType",
                Val: "Rr214"
            }, {
                Desc: "TotalAmt",
                Val: "Rr215"
            }, {
                Desc: "RealAmt",
                Val: "Rr216"
            }, {
                Desc: "RefundAmt",
                Val: "Rr217"
            }, {
                Desc: "TransDate",
                Val: "Rr218"
            }]
        },
        {
            Desc: "BatchTids",
            Val: "R027",
            Rr: [{
                Desc: "StoreId",
                Val: "Rr221"
            }, {
                Desc: "StoreName",
                Val: "Rr222"
            }, {
                Desc: "Tid",
                Val: "Rr223"
            }, {
                Desc: "StoreMobile",
                Val: "Rr224"
            }, {
                Desc: "StoreUserName",
                Val: "Rr225"
            }, {
                Desc: "StoreAddr",
                Val: "Rr226"
            }, {
                Desc: "KcStoreId",
                Val: "Rr227"
            }, {
                Desc: "KcTid",
                Val: "Rr228"
            }, {
                Desc: "KcItemCode",
                Val: "Rr229"
            }]
        },

        {
            Desc: "StoreBizReport",
            Val: "R028",
            Rr: [
                {
                    Desc: "StoreId",
                    Val: "Rr230"
                },
                {
                    Desc: "StoreName",
                    Val: "Rr231"
                },
                {
                    Desc: "StoreType",
                    Val: "Rr232"
                },
                {
                    Desc: "Mobile",
                    Val: "Rr233"
                },
                {
                    Desc: "Area",
                    Val: "Rr234"
                },
                {
                    Desc: "Cnt",
                    Val: "Rr235"
                },
                {
                    Desc: "Amt",
                    Val: "Rr236"
                },
                {
                    Desc: "LastDate",
                    Val: "Rr237"
                },
                {
                    Desc: "CreatDate",
                    Val: "Rr238"
                }
            ]
        },

        {
            Desc: "GoodsReport",
            Val: "R029",
            Rr: [
                {
                    Desc: "TransDate",
                    Val: "Rr238"
                },
                {
                    Desc: "GoodsId",
                    Val: "Rr239"
                },
                {
                    Desc: "GoodsName",
                    Val: "Rr240"
                },
                {
                    Desc: "GoodsTotNum",
                    Val: "Rr241"
                },
                {
                    Desc: "GoodsTotAmt",
                    Val: "Rr242"
                },
                {
                    Desc: "StoreId",
                    Val: "Rr243"
                },
                {
                    Desc: "StoreName",
                    Val: "Rr244"
                },
            ]
        },

        {
            Desc: "gdtypeReport",
            Val: "R030",
            Rr: [
                {
                    Desc: "TransDate",
                    Val: "Rr245"
                },
                {
                    Desc: "GoodsType",
                    Val: "Rr246"
                },
                {
                    Desc: "GoodsTypeName",
                    Val: "Rr247"
                },
                {
                    Desc: "GoodsTotNum",
                    Val: "Rr248"
                },
                {
                    Desc: "GoodsTotAmt",
                    Val: "Rr249"
                },
                {
                    Desc: "StoreId",
                    Val: "Rr250"
                },
                {
                    Desc: "StoreName",
                    Val: "Rr251"
                },
            ]
        },
        {
            Desc: "Partners",
            Val: "R031",
            Rr: [{
                Desc: "PartnersInstId",
                Val: "Rr301"
            }, {
                Desc: "PartnersInstName",
                Val: "Rr302"
            }, {
                Desc: "PartnersInstLogo",
                Val: "Rr303"
            }, {
                Desc: "PartnersInstTitleName",
                Val: "Rr304"
            }]
        }
    ],

    Y: [{
        Desc: "AddDate",
        Val: "Y001"
    }, {
        Desc: "AllCount",
        Val: "Y002"
    }, {
        Desc: "AllPage",
        Val: "Y003"
    }, {
        Desc: "AllRefundAmt",
        Val: "Y004"
    }, {
        Desc: "BegDate",
        Val: "Y005"
    }, {
        Desc: "CalcType",
        Val: "Y006"
    }, {
        Desc: "ChannelFlag",
        Val: "Y007"
    }, {
        Desc: "CustQryNum",
        Val: "Y008"
    }, {
        Desc: "CurCount",
        Val: "Y009"
    }, {
        Desc: "CurPage",
        Val: "Y010"
    }, {
        Desc: "EditDate",
        Val: "Y011"
    }, {
        Desc: "EndDate",
        Val: "Y012"
    }, {
        Desc: "Flag",
        Val: "Y013"
    }, {
        Desc: "FunctionNum",
        Val: "Y014"
    }, {
        Desc: "GoodsCount",
        Val: "Y015"
    }, {
        Desc: "GoodsTypeCount",
        Val: "Y016"
    }, {
        Desc: "Id",
        Val: "Y017"
    }, {
        Desc: "Issuid",
        Val: "Y018"
    }, {
        Desc: "NewMobile",
        Val: "Y019"
    }, {
        Desc: "NewPwd",
        Val: "Y020"
    }, {
        Desc: "NewVeriCode",
        Val: "Y021"
    }, {
        Desc: "Num",
        Val: "Y022"
    }, {
        Desc: "OriMobile",
        Val: "Y023"
    }, {
        Desc: "OriVeriCode",
        Val: "Y024"
    }, {
        Desc: "OwnerFlag",
        Val: "Y025"
    }, {
        Desc: "OrderBy",
        Val: "Y026"
    }, {
        Desc: "OrderFlag",
        Val: "Y027"
    }, {
        Desc: "OrgPayId",
        Val: "Y028"
    }, {
        Desc: "OrgTransId",
        Val: "Y029"
    }, {
        Desc: "PayAccount",
        Val: "Y030"
    }, {
        Desc: "PayCount",
        Val: "Y031"
    }, {
        Desc: "PayId",
        Val: "Y032"
    }, {
        Desc: "PayMode",
        Val: "Y033"
    }, {
        Desc: "PaySeq",
        Val: "Y034"
    }, {
        Desc: "PayStatus",
        Val: "Y035"
    }, {
        Desc: "PayType",
        Val: "Y036"
    }, {
        Desc: "SsPackReqTime",
        Val: "Y037"
    }, {
        Desc: "SsPackReqCasher",
        Val: "Y038"
    }, {
        Desc: "PurchasePrice",
        Val: "Y039"
    }, {
        Desc: "RealAmt",
        Val: "Y040"
    }, {
        Desc: "RefundAmt",
        Val: "Y041"
    }, {
        Desc: "RefundNum",
        Val: "Y042"
    }, {
        Desc: "RespCode",
        Val: "Y043"
    }, {
        Desc: "AssociatorPrice",
        Val: "Y044"
    }, {
        Desc: "SaleId",
        Val: "Y045"
    }, {
        Desc: "SsPackResCasher",
        Val: "Y046"
    }, {
        Desc: "Status",
        Val: "Y047"
    }, {
        Desc: "SsPackResTime",
        Val: "Y048"
    }, {
        Desc: "StockControl",
        Val: "Y049"
    }, {
        Desc: "StoreId",
        Val: "Y050"
    }, {
        Desc: "TxnId",
        Val: "Y051"
    }, {
        Desc: "TxnType",
        Val: "Y052"
    }, {
        Desc: "Tid",
        Val: "Y053"
    }, {
        Desc: "TotalAmt",
        Val: "Y054"
    }, {
        Desc: "TransAllAmt",
        Val: "Y055"
    }, {
        Desc: "TransAmt",
        Val: "Y056"
    }, {
        Desc: "TransDate",
        Val: "Y057"
    }, {
        Desc: "TransType",
        Val: "Y058"
    }, {
        Desc: "TransId",
        Val: "Y059"
    }, {
        Desc: "UnitCount",
        Val: "Y060"
    }, {
        Desc: "UptStockDate",
        Val: "Y061"
    }, {
        Desc: "UserId",
        Val: "Y062"
    }, {
        Desc: "UserMobile",
        Val: "Y063"
    }, {
        Desc: "UserPwd",
        Val: "Y064"
    }, {
        Desc: "Uuid",
        Val: "Y065"
    }, {
        Desc: "VeriCode",
        Val: "Y066"
    }, {
        Desc: "WholesalePrice",
        Val: "Y067"
    }, {
        Desc: "TypeId",
        Val: "Y068"
    }, {
        Desc: "Img",
        Val: "Y069"
    }, {
        Desc: "Spec",
        Val: "Y070"
    }, {
        Desc: "RetailPrice",
        Val: "Y071"
    }, {
        Desc: "StockFlag",
        Val: "Y072"
    }, {
        Desc: "Stock",
        Val: "Y073"
    }, {
        Desc: "UnitName",
        Val: "Y074"
    }, {
        Desc: "RoleId",
        Val: "Y075"
    }, {
        Desc: "RolesNum",
        Val: "Y076"
    }, {
        Desc: "SpcifyUserId",
        Val: "Y077"
    }, {
        Desc: "StoresCount",
        Val: "Y079"
    }, {
        Desc: "BarCode",
        Val: "Y080"
    }, {
        Desc: "BarCodeImg",
        Val: "Y081"
    }, {
        Desc: "ShareFlag",
        Val: "Y082"
    }, {
        Desc: "SpcifyStoreId",
        Val: "Y083"
    }, {
        Desc: "ParentStoreId",
        Val: "Y084"
    }, {
        Desc: "StoreLevel",
        Val: "Y085"
    }, {
        Desc: "StoreChildNum",
        Val: "Y086"
    }, {
        Desc: "StoreCurChildNum",
        Val: "Y087"
    }, {
        Desc: "StoreTidNum",
        Val: "Y088"
    }, {
        Desc: "StoreCurTidNum",
        Val: "Y089"
    }, {
        Desc: "CreateDate",
        Val: "Y090"
    }, {
        Desc: "ModifyDate",
        Val: "Y091"
    }, {
        Desc: "StoreMid",
        Val: "Y092"
    }, {
        Desc: "CopyGoodsFlag",
        Val: "Y093"
    }, {
        Desc: "StoreUserId",
        Val: "Y094"
    }, {
        Desc: "MacKey",
        Val: "Y097"
    }, {
        Desc: "RsaKeylen",
        Val: "Y099"
    }, {
        Desc: "CPubKey",
        Val: "Y100"
    }, {
        Desc: "SPubKey",
        Val: "Y101"
    }, {
        Desc: "JsCode",
        Val: "Y103"
    }, {
        Desc: "TidFlag",
        Val: "Y104"
    }, {
        Desc: "QrCodeUniVal",
        Val: "Y105"
    }, {
        Desc: "SpcifyTid",
        Val: "Y106"
    }, {
        Desc: "PyCode",
        Val: "Y107"
    }, {
        Desc: "CurAmt",
        Val: "Y108"
    }, {
        Desc: "CurCnt",
        Val: "Y109"
    }, {
        Desc: "YesAmt",
        Val: "Y110"
    }, {
        Desc: "YesCnt",
        Val: "Y111"
    }, {
        Desc: "MonAmt",
        Val: "Y112"
    }, {
        Desc: "MonCnt",
        Val: "Y113"
    }, {
        Desc: "RTransCount",
        Val: "Y118"
    }, {
        Desc: "SpcifyMobile",
        Val: "Y126"
    }, {
        Desc: "LoginId",
        Val: "Y136"
    }, {
        Desc: "LoginStatus",
        Val: "Y137"
    }, {
        Desc: "UserName",
        Val: "Y138"
    }, {
        Desc: "FuncId",
        Val: "Y139"
    }, {
        Desc: "FuncParentId",
        Val: "Y140"
    }, {
        Desc: "FuncName",
        Val: "Y141"
    }, {
        Desc: "FuncDesc",
        Val: "Y142"
    }, {
        Desc: "FuncStatus",
        Val: "Y143"
    }, {
        Desc: "TransChannel",
        Val: "Y147"
    }, {
        Desc: "FunctionMap",
        Val: "Y150"
    }, {
        Desc: "PayTypeMap",
        Val: "Y151"
    }, {
        Desc: "SpcGrpId",
        Val: "Y165"
    },
        {
            Desc: "StoretypeId",
            Val: "Y195"
        },
        {
            Desc: "LinkMan",
            Val: "Y196"
        }, {
            Desc: "Teller",
            Val: "Y197"
        }, {
            Desc: "UserLvl",
            Val: "Y199"
        }, {
            Desc: "KcStoreId",
            Val: "Y200"
        }, {
            Desc: "KcTid",
            Val: "Y201"
        }, {
            Desc: "KcItemCode",
            Val: "Y202"
        }, {
            Desc: "SumTotalAmt",
            Val: "Y203"
        }, {
            Desc: "SumRealAmt",
            Val: "Y204"
        }, {
            Desc: "SumRefundAmt",
            Val: "Y205"
        }, {
            Desc: "SumCnt",
            Val: "Y206"
        }, {
            Desc: "SumAmt",
            Val: "Y207"
        },
        {
            Desc: "LastBegDate",
            Val: "Y208"
        },
        {
            Desc: "LastEndDate",
            Val: "Y209"
        },
        {
            Desc: "ParterId",
            Val: "Y301"
        },
        {
            Desc: "ParterLogo",
            Val: "Y302"
        }
    ],
    S: [{
        Desc: "RptSumUserRgst",
        Val: "S001"
    }, {
        Desc: "RptSumStoreRgst",
        Val: "S002"
    }, {
        Desc: "RptSumTidRgst",
        Val: "S003"
    }, {
        Desc: "RptSumGoodsAdd",
        Val: "S004"
    }, {
        Desc: "RptSumGdsAddS",
        Val: "S005"
    }, {
        Desc: "RptSumMobileLg",
        Val: "S006"
    }, {
        Desc: "RptSumPosLg",
        Val: "S007"
    }, {
        Desc: "RptSumTransCnt",
        Val: "S008"
    }, {
        Desc: "RptSumTransTotalAmt",
        Val: "S009"
    }, {
        Desc: "RptSumTransRealAmt",
        Val: "S010"
    }, {
        Desc: "RptSumRTransCnt",
        Val: "S011"
    }, {
        Desc: "RptSumRTransTotalAmt",
        Val: "S012"
    }, {
        Desc: "RptSumRTransRealAmt",
        Val: "S013"
    }, {
        Desc: "RptSumSaleCnt",
        Val: "S014"
    }, {
        Desc: "RptSumSaleAmt",
        Val: "S015"
    }, {
        Desc: "RptSumRefCnt",
        Val: "S016"
    }, {
        Desc: "RptSumRefAmt",
        Val: "S017"
    }],
    Z: [{
        Desc: "RespDesc",
        Val: "Z1"
    }, {
        Desc: "SignValue",
        Val: "Z2"
    }, {
        Desc: "Addr",
        Val: "Z3"
    }, {
        Desc: "Area",
        Val: "Z4"
    }, {
        Desc: "City",
        Val: "Z5"
    }, {
        Desc: "Name",
        Val: "Z6"
    }, {
        Desc: "Province",
        Val: "Z7"
    }, {
        Desc: "GoodsMemo",
        Val: "Z8"
    }, {
        Desc: "RoleDesc",
        Val: "Z9"
    }, {
        Desc: "TradeMark",
        Val: "Z10"
    }, {
        Desc: "ManuName",
        Val: "Z11"
    }, {
        Desc: "Producer",
        Val: "Z12"
    }, {
        Desc: "ManuAddress",
        Val: "Z13"
    }, {
        Desc: "SGoodsTypeName",
        Val: "Z14"
    }, {
        Desc: "RoleName",
        Val: "Z15"
    }, {
        Desc: "ParterTitleName",
        Val: "Z101"
    }]
};
